/** @format */

export const brandImages = [
  {
    id: 1,
    name: "JM Internacional",
    logo: "/jm-logo-transparent-bg-min.webp",
    owned: true,
    description: "",
    descriptionES: "",
  },
  {
    id: 2,
    name: "Eagle Parts",
    logo: "/eaglePartsLogo.webp",
    owned: true,
    description:
      "Eagle Chassis Parts is our line of wide portfolio of products for the chassis of your heavy equipment. These include brake shoes and brake shoe kits, brake drums, rims, wheel clamps, wheel studs, inner nuts, landing gear, fifth wheels, springs, suspension bushings, suspension bars, equalizers, spring hangers, insulator pads, trunnion, bases, spring saddles, U-bolt kits, spring pins, tie rod end, drag links, King pin sets. Eagle Chassis Parts is supplied by original equipment manufacturers and each component has been previously tested so that the quality and performance is adequate for our American roads, which demand high performance products.",
    descriptionES:
      "Eagle Chassis Parts es nuestra línea de amplio portafolio de productos para el chasis de su equipo pesado. Estos incluyen zapatas de freno y juegos de zapatas de freno, tambores de freno, llantas, abrazaderas de rueda, espárragos de rueda, tuercas internas, patas de aterrizaje, quintas ruedas, resortes, bujes de suspensión, barras de suspensión, ecualizadores, soportes de resorte, almohadillas aislantes, trunnion, bases, sillas de resorte, juegos de pernos en U, pasadores de resorte, extremos de varilla de dirección, barras de arrastre, juegos de pasadores rey. Eagle Chassis Parts es suministrado por fabricantes de equipos originales y cada componente ha sido previamente probado para asegurar que la calidad y el rendimiento sean adecuados para nuestras carreteras estadounidenses, que exigen productos de alto rendimiento.",
  },
  {
    id: 3,
    name: "Quantum Trux Parts",
    logo: "/quantumTruxPartsLogo.webp",
    owned: true,
    description:
      "Quantum is our line of spare parts and accessories for heavy equipment. Among them are parts for drive shaft, air systems, axles and wheels, electrical components, accessories for doors, mirrors and chrome accessories, tarps and cargo straps, exhaust, hood latches, mud flaps and mud flaps hangers, cables, radiator, flywheels, fuel transfer pumps, crown and pinion, filters and filter covers, bumper and fenders, backup alarms and telescopic cylinders. The Quantum line is supplied by original equipment manufacturers, with excellent quality and performance.",
    descriptionES:
      "Quantum es nuestra línea de repuestos y accesorios para equipos pesados. Entre ellos se encuentran piezas para el eje de transmisión, sistemas de aire, ejes y ruedas, componentes eléctricos, accesorios para puertas, espejos y accesorios cromados, lonas y correas de carga, escapes, seguros para el capó, guardabarros y soportes para guardabarros, cables, radiador, volantes de inercia, bombas de transferencia de combustible, coronas y piñones, filtros y cubiertas para filtros, parachoques y guardabarros, alarmas de retroceso y cilindros telescópicos. La línea Quantum es suministrada por fabricantes de equipos originales, con excelente calidad y rendimiento.",
  },
  {
    id: 4,
    name: "USA PRO",
    logo: "/usaProLogo.webp",
    owned: true,
    description:
      "USA Pro is our new line of engine parts. Extensively tested and guaranteed performance. This line includes products such as: engine liners, connecting rod bearings, camshaft components, valve guides, exhaust valves, intake valves, valve seats, pistons and piston rings, seals, gaskets, fuel pumps, water temperature sensors, coolant tanks, oil coolers, injector sleeves, oil pumps, oil sensors, engine valves, turbos, crankshaft components, sprinklers. Our USA Pro products go above and beyond to ensure your heavy equipment keeps working.",
    descriptionES:
      "USA Pro es nuestra nueva línea de piezas de motor. Ampliamente probada y garantizada para un rendimiento óptimo. Esta línea incluye productos como revestimientos de motor, cojinetes de biela, componentes de árbol de levas, guías de válvula, válvulas de escape, válvulas de admisión, asientos de válvula, pistones y segmentos de pistón, sellos, juntas, bombas de combustible, sensores de temperatura del agua, tanques de refrigerante, enfriadores de aceite, casquillos de inyector, bombas de aceite, sensores de aceite, válvulas de motor, turbos, componentes de cigüeñal y rociadores. Nuestros productos USA Pro van más allá para garantizar que su equipo pesado siga funcionando a la perfección.",
  },
  {
    id: 5,
    name: "GoodYear",
    logo: "/goodyear.jfif",
    owned: false,
    description:
      "Goodyear air springs for your truck or trailer will offer a quiet, more cushioned ride resulting in greater comfort, peace of mind, and safety. Due to less vibration, truck and trailer suspension components will last longer while providing durability and improved protection from shock and vibration for the vehicle, passenger, and cargo.",
    descriptionES:
      "Los resortes de aire Goodyear para su camión o remolque ofrecerán un viaje más tranquilo y acolchado, lo que resultará en mayor comodidad, tranquilidad y seguridad. Debido a una menor vibración, los componentes de suspensión del camión y el remolque durarán más, al tiempo que proporcionarán durabilidad y una protección mejorada contra golpes y vibraciones para el vehículo, los pasajeros y la carga.",
  },
  {
    id: 6,
    name: "GRC",
    logo: "/grc.png",
    owned: false,
    description:
      "The demand placed on today's heavy trucks, trailers and buses place severe stress on their suspension systems. Now more than ever it is essential to have high performance shocks that you can trust. That's why so many heavy trucks are running on FleetlineTM GRC® shocks. FleetlineTM products are made to be direct replacements for Original Equipment shocks because they are designed to meet or exceed OEM specifications and quality standards.",
    descriptionES:
      "La demanda que se coloca en los camiones pesados, remolques y autobuses actuales ejerce un estrés severo en sus sistemas de suspensión. Ahora, más que nunca, es esencial contar con amortiguadores de alto rendimiento en los que pueda confiar. Por eso, muchos camiones pesados están utilizando los amortiguadores FleetlineTM GRC®. Los productos FleetlineTM están diseñados para ser reemplazos directos de los amortiguadores de Equipo Original, ya que están diseñados para cumplir o superar las especificaciones y estándares de calidad del OEM.",
  },
  {
    id: 7,
    name: "Triseal",
    logo: "/triseal.jfif",
    owned: false,
    description: "Pending description...",
    descriptionES: "Descripción pendiente...",
  },
  {
    id: 9,
    name: "Eaton",
    logo: "/roadranger-eaton.jfif",
    owned: false,
    description: "Pending description...",
    descriptionES: "Descripción pendiente...",
  },
  {
    id: 9,
    name: "Sampa",
    logo: "/sampa.png",
    owned: false,
    description:
      "Sampa was established in 1994 as a distributer in a 100 m2 shop with a production and industry expertise that dates back to 1950. Since then, the company has transformed into a unique manufacturing, procurement and sales giant, operating on a 100.000 m2 integrated factory campus. Sampa now develops and manufactures long-lasting, highly durable parts with unique materials for the aftermarket, suitable for European and American heavy-duty vehicles, trailers, buses, and minivans.",
    descriptionES:
      "Sampa fue fundada en 1994 como distribuidor en una tienda de 100 m2, con experiencia en producción e industria que se remonta a 1950. Desde entonces, la empresa se ha transformado en un gigante único en fabricación, adquisiciones y ventas, operando en un campus de fábrica integrada de 100.000 m2. Sampa ahora desarrolla y fabrica piezas de larga duración y altamente resistentes con materiales únicos para el mercado de repuestos, adecuadas para vehículos pesados, remolques, autobuses y furgonetas europeos y estadounidenses.",
  },
];

export const products = [
  {
    brand: "eagleparts",
    logo: "/eaglePartsLogo.webp",
    id: 1,
    products: [
      {
        id: 1,
        name: "Eagle Parts",
        title: "EAG-TCR5572",
        images: ["/EAG-TCR5572 - 400px.png"],
        description: "Cuña de rueda trasera, mediana Wheel Clamp",
        replacement: ["E5571A", "09-612317", "W-96", "52-1301", "R005571AG"],
      },
      {
        id: 2,
        name: "Eagle Parts",
        title: "EAG-TTT3414",
        images: ["/EAG-TTT3414 - 400px.png"],
        description:
          "Kit de Tornillo Para Balancin tipo Hutch Equalizer Bolt Kit",
      },
      {
        id: 3,
        name: "Eagle Parts",
        title: "EAG-SSB2718",
        images: ["/EAG-SSB2781 - 400px.png"],
        description: "",
      },
      {
        id: 4,
        name: "Eagle Parts",
        title: "EAG-RTF6864",
        images: ["/EAG-RTF6864 - 400px.png"],
        description:
          "Tambor de Freno Wheel Brake Drum Rear 16.50 x 7.0, Hub Pilot, 8.78” Pilot ",
      },
      {
        id: 5,
        name: "Eagle Parts",
        title: "EAG-SBT2889",
        images: ["/EAG-SBT2899 - 400px.png"],
        description: "Barra fija para Hutchens Rigid Torque Arm",
      },
      {
        id: 6,
        name: "Eagle Parts",
        title: "EAG-FQR3003",
        images: ["/newImages/EAG-FQR3003-min.png"],
        description: "Quinta Rueda Tipo Holland Con base incluida.",
        descriptionES: "Fifth Wheel, Holland type w/ base included",
        replacement: ["BP3003"],
      },
      {
        id: 7,
        name: "Eagle Parts",
        title: "EAG-FQR0050",
        images: ["/newImages/EAG-FQR0050-min.png"],
        description: "Pin Para Quinta Rueda",
        descriptionES: "Fifth Wheel Coupling Pin",
        replacement: ["CM-W50"],
      },
      {
        id: 8,
        name: "Eagle Parts",
        title: "EAG-FQR7296",
        images: ["/newImages/EAG-FQR7296-min.png"],
        description: "Kit de Repación para Quinta Rueda Holland",
        descriptionES: "Holland Fifth Wheel Minor Repair Kit",
        replacement: ["RK35107296"],
      },
      {
        id: 9,
        name: "Eagle Parts",
        title: "EAG-FPF6110",
        images: ["/newImages/EAG-FPF6110-min.png"],
        description: "Juego Patas de Furgon, Reforzadas, 30T",
        descriptionES: "30 Tons Landing Gear",
        replacement: ["26110"],
      },
      {
        id: 10,
        name: "Eagle Parts",
        title: "EAG-FPF0001",
        images: ["/newImages/EAG-FPF0001-min.png"],
        description: "Patin para Patas Furgón",
        descriptionES: "Landing Gear Sand Shoe",
      },
      {
        id: 11,
        name: "Eagle Parts",
        title: "EAG-HRR2727",
        images: ["/newImages/EAG-HRR2727-min.png"],
        description: "Resorte de 3 Hojas de media curva",
        descriptionES: "Trailer Spring 3 Leaf, Medium 4-1/2″ Arch.",
        replacement: ["TRA-2727"],
      },
      {
        id: 12,
        name: "Eagle Parts",
        title: "EAG-SBT2639",
        images: ["/newImages/EAG-SBT2639-min.png"],
        description: "Barra Tensora Hembra con Buje de 2.75, hueco 5/8″",
        descriptionES: "Two Piece Torque Rod End",
        replacement: ["E2639", "TMRU610 (Automann)"],
      },
      {
        id: 13,
        name: "Eagle Parts",
        title: "EAG-SSB2830",
        images: ["/newImages/EAG-SSB2830-min.png"],
        description: "BALANCIN FREUHAUF",
        descriptionES: "Fruehauf F-2 Equalizer",
        replacement: ["E2830", "338-715", "FR-2691", "EQ015"],
      },
      {
        id: 14,
        name: "Eagle Parts",
        title: "EAG-SBT5680",
        images: ["/newImages/EAG-SBT5680-min.png"],
        description:
          "Barra Tensora macho (Hasta 35″) con Altura 8″ y Rosca 1-1/4″-12",
        descriptionES:
          "Torque Rod End (Up to 35″), H:  8″, THREADS:  1-1/4″-12",
        replacement: ["TMRU680", "Dayton 345-680", "Flagg MR680"],
      },
      {
        id: 15,
        name: "Eagle Parts",
        title: "EAG-SCS2919PU",
        images: ["/newImages/EAG-SCS2919PU-min.png"],
        description: "Sapo Mediano (Superior) Poliuretano",
        descriptionES: "Mack Insulator Pad Poly",
        replacement: ["10QK370-UB"],
      },
      {
        id: 16,
        name: "Eagle Parts",
        title: "EAG-DTD0411R",
        images: ["/newImages/EAG-DTD0411R-min.png"],
        description: "Terminal de direccion Inter Largo",
        descriptionES: "Outer Tie Rod End (RH) 9.18″",
        replacement: ["ES-411R"],
      },
      {
        id: 17,
        name: "Eagle Parts",
        title: "EAG-DTB4272",
        images: ["/newImages/EAG-DTB4272-min.png"],
        description: "Tercer Brazo Mack CH (34.75″ nominal /centro a centro)",
        descriptionES: "Drag Link for Mack  - 34.75″",
        replacement: ["MAK13QC427AM2"],
      },
      {
        id: 18,
        name: "Eagle Parts",
        title: "EAG-DBT2514",
        images: ["/newImages/EAG-DBT2514-min.png"],
        description: "Brazo de Torque Fijo",
        descriptionES: "Rigid Torque Arm 15-7/16 Center To Center",
        replacement: ["E2514"],
      },
      {
        id: 19,
        name: "Eagle Parts",
        title: "EAG-DTB3426",
        images: ["/newImages/EAG-DTB3426-min.png"],
        description: "Tercer Brazo (Barra de Arrastre) 18 3/4″ centro a centro",
        descriptionES: "Drag Link for Mack - 18.75″",
        replacement: ["MAK-13QC426A", "Dayton 346-578"],
      },
      {
        id: 20,
        name: "Eagle Parts",
        title: "EAG-DTB5366",
        images: ["/newImages/EAG-DTB5366-min.png"],
        description: "Tercer Brazo Navistar Stud Center-Stud Center: 18.14”",
        descriptionES: "Drag Link for International - 18.14”",
        replacement: [
          "E5366",
          "DS-979",
          "Dayton:  346-249",
          "Navistar:  480645C92",
        ],
      },
    ],
  },
  {
    brand: "quantumTruxParts",
    logo: "/quantumTruxPartsLogo.webp",
    id: 2,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-EMC1003",
        images: ["/QTM-EMC1003 - 400px.png"],
        description: "Cruceta 6 U-Joint 1710 Series",
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-EMB1101",
        images: ["/QTM-EMB1101 - 400px.png"],
        description:
          "Balinera de Centro (Soporte de Cardán) Driveshaft Center Support Bearing",
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-ARV2100",
        images: ["/QTM-ARV2100 - 400px.png"],
        description: "Valvula de Reparto R-12H Relay Valve R-12H",
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-BBT8706",
        images: ["/QTM-BBT8706 - 400px.png"],
        description:
          "Bomba de transferencia de combustible para 1997-2006 Mack E7E Fuel transfer pump for 1997-2006 Mack E7E",
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-LLU4009B",
        images: ["/QTM-LLU4009B - 400px.png"],
        description:
          "Lámpara de 32 LED de 4in / 12 V BLANCA 4in LED Lamp, 32 LEDS, 12v, WHITE",
      },
      {
        id: 6,
        name: "Quantum Trux Parts",
        title: "QTM-EMC1006",
        images: ["/newImages/QTM-EMC1006-min.png"],
        description: "Cruceta de 6' Mixta Serie 1710",
        descriptionES: "U-Joint 1710 Series Half Round Yoke",
        replacement: ["Precision: 476", "Spicer: 5-675X", "NewStar: S-C473"],
      },
      {
        id: 7,
        name: "Quantum Trux Parts",
        title: "QTM-EMG1022",
        images: ["/newImages/QTM-EMG1022-min.png"],
        description: "Grapas para crucetas SPL170X",
        descriptionES: "SPL170 Strap & Bolt Kit SPL170X",
        replacement: ["Spicer: 170-70-18X", "S&S Truck: S-D757"],
      },
      {
        id: 8,
        name: "Quantum Trux Parts",
        title: "QTM-EMC1017",
        images: ["/newImages/QTM-EMC1017-min.png"],
        description: "Cruceta",
        descriptionES: "U Joint SPL90 Series Greasable",
        replacement: ["Spicer:  SPL90X"],
      },
      {
        id: 9,
        name: "Quantum Trux Parts",
        title: "QTM-EMB1102",
        images: ["/newImages/QTM-EMB1102-min.png"],
        description: "Balinera de Centro (Soporte de Cardán) Serie 1710",
        descriptionES: "Driveshaft Center Support Bearing",
        replacement: [
          "Federal:  HB88510",
          "Precision: HPE9880",
          "Spicer:  210121-1X",
          "NewStar:  S-1980",
        ],
      },
      {
        id: 10,
        name: "Quantum Trux Parts",
        title: "QTM-EMR1104",
        images: ["/newImages/QTM-EMR1104-min.png"],
        description: "Caucho Balinera de Centro HB88508",
        descriptionES: "Rubber Cushion for HB88508",
      },
      {
        id: 11,
        name: "Quantum Trux Parts",
        title: "QTM-ASA2021",
        images: ["/newImages/QTM-ASA2021-min.png"],
        description: "Secador de Aire, AD9",
        descriptionES:
          "Air Dryer (Supply Port (1) 1/2 'P.T.  Delivery Port (1) 1/2' P.T.)",
        replacement: ["LAD-5586", "Bendix: 065225"],
      },
      {
        id: 12,
        name: "Quantum Trux Parts",
        title: "QTM-APV2051",
        images: ["/newImages/QTM-APV2051-min.png"],
        description: "Válvula E6 con Pedal y Base",
        descriptionES: "E6 Foot Valve with Pedal and Base",
        replacement: ["5396-SN4017A", "FA-11016"],
      },
      {
        id: 13,
        name: "Quantum Trux Parts",
        title: "QTM-ATC2751",
        images: ["/newImages/QTM-ATC2751-min.png"],
        description: "Válvula de control-Doble Válvula (Pto & Dump Pump)",
        descriptionES: "PTO/Dump Pump Combo Valve",
        replacement: ["S-D522", "329358X"],
      },
      {
        id: 14,
        name: "Quantum Trux Parts",
        title: "QTM-AVN2715",
        images: ["/newImages/QTM-AVN2715-min.png"],
        description: "Valvula Niveladora Tipo Retardo CV",
        descriptionES: "Leveling Delay Type CV",
        replacement: ["MACK: 20QE2373"],
      },
      {
        id: 15,
        name: "Quantum Trux Parts",
        title: "QTM-AFS2653",
        images: ["/newImages/QTM-AFS2653-min.png"],
        description: "Valvula de Freno ABS Completa",
        descriptionES: "ABS Axle Package Assy",
      },
      {
        id: 16,
        name: "Quantum Trux Parts",
        title: "QTM-RRT3108",
        images: ["/newImages/QTM-RRT3108-min.png"],
        description: "Retenedora de Rueda  para ejes de 34,000",
        descriptionES: "Oil Bath Wheel Seal ",
        replacement: ["370023A"],
      },
      {
        id: 17,
        name: "Quantum Trux Parts",
        title: "QTM-RTR3215",
        images: ["/newImages/QTM-RTR3215-min.png"],
        description: "TAPA DE 6 HUECOS",
        descriptionES: "Cast Aluminum Hub Cap",
      },
      {
        id: 18,
        name: "Quantum Trux Parts",
        title: "QTM-CMP6008",
        images: ["/newImages/QTM-CMP6008-min.png"],
        description:
          "Manigueta Exterior de Puerta para Freightliner Columbia y Century (Llavín incluído) Izq.",
        descriptionES: "Door Handle, LH Columbia Class (1998-2003)",
        replacement: ["A18-42228-000", "New Star:  S-18817"],
      },
      {
        id: 19,
        name: "Quantum Trux Parts",
        title: "QTM-CCP6050",
        images: ["/newImages/QTM-CCP6050-min.png"],
        description: "Cerradura para Puerta Derecha para Mack DM, R y U",
        descriptionES: "Door Latch (RH) for Mack R/RB/RD/DM Models",
        replacement: ["MAK 62QS423R"],
      },
      {
        id: 20,
        name: "Quantum Trux Parts",
        title: "QTM-CES6149",
        images: ["/newImages/QTM-CES6149 - 50-min.png"],
        description: "Espejo para Capota VOLVO Cromado Izq.",
        descriptionES: "Hood Mirror for VOLVO CHROME L",
        replacement: ["01-110055CH"],
      },
      {
        id: 21,
        name: "Quantum Trux Parts",
        title: "QTM-CPA6216",
        images: ["/newImages/QTM-CPA6216-min.png"],
        description: "Parrilla para International PROSTAR",
        descriptionES: "Truck Front Grill forPROSTAR International",
        replacement: ["01-210001"],
      },
      {
        id: 22,
        name: "Quantum Trux Parts",
        title: "QTM-CBS6317",
        images: ["/newImages/QTM-CBS6317 - 18-min.png"],
        description: "Bisel Cromado para International Serie 9,000 Izq.",
        descriptionES: "Headlight Bezel for  International 9,000 Series (LH)",
        replacement: ["Newstar: S-21412", "Inter: 2505-370-C"],
      },
      {
        id: 23,
        name: "Quantum Trux Parts",
        title: "QTM-XDE8002",
        images: ["/newImages/QTM-XDE8002-min.png"],
        description: "Codo de 5″ x90 de patas largas",
        descriptionES:
          "Exhaust Elbow-5″ 90 Degree Elbow 20″ x 20″ ID-OD – Aluminized",
        replacement: ["11ME241"],
      },
      {
        id: 24,
        name: "Quantum Trux Parts",
        title: "QTM-XAH8364",
        images: ["/newImages/QTM-XAH8364-min.png"],
        description: "Abrazadera de 5″ Para Turbo Con Labio",
        descriptionES: "5″ Turbo Outlet Clamp",
      },
      {
        id: 25,
        name: "Quantum Trux Parts",
        title: "QTM-XRD8033",
        images: ["/newImages/QTM-XRD8033-min.png"],
        description: "Reducción 5″ a 4″",
        descriptionES:
          "Connector-Reducer Coupler Aluminized 5″ ID to 4″ ID x 6″ Long",
        replacement: ["RI540"],
      },
      {
        id: 26,
        name: "Quantum Trux Parts",
        title: "QTM-XFT8251",
        images: ["/newImages/QTM-XFT8251-min.png"],
        description: "Tubo Flexible de 5″ (25 pies por rollo)",
        descriptionES: "Heavy Weight Flexible Tubing 5″ x 25'",
      },
      {
        id: 27,
        name: "Quantum Trux Parts",
        title: "QTM-XSM8300",
        images: ["/newImages/QTM-XSM8300-min.png"],
        description: "Silenciador 51″x10″x5″x5″44.5″",
        descriptionES: "Horizontal or Vertical Muffler 51″x10″x5″x5″44.5″",
        replacement: ["5839-86682M"],
      },
      {
        id: 28,
        name: "Quantum Trux Parts",
        title: "QTM-CTR6760",
        images: ["/newImages/QTM-CTR6760-min.png"],
        description: "anque de Refrigerante para MACK GU Y CV",
        descriptionES: "Coolant tank for MACK GU Y CV",
        replacement: ["22061290"],
      },
      {
        id: 29,
        name: "Quantum Trux Parts",
        title: "QTM-CTC6714",
        images: ["/newImages/QTM-CTC6714-min.png"],
        description: "Tapa Tanque de Expansión de Líquido Refrigerante M2",
        descriptionES: "Surge Tank Cap M2",
        replacement: ["05-180002", "M2"],
      },
      {
        id: 30,
        name: "Quantum Trux Parts",
        title: "QTM-RRF8506",
        images: ["/newImages/QTM-RRF8506-min.png"],
        description: "Radiador",
        descriptionES:
          "Radiator Freightliner Century, Columbia and Classic XL 2008-2011 (987x958.1x58x63.5/63.5)",
        replacement: ["05-26619-024"],
      },
      {
        id: 31,
        name: "Quantum Trux Parts",
        title: "QTM-RIC8551",
        images: ["/newImages/QTM-RIC8551-min.png"],
        description:
          "Intercooler for Freightliner FLD112 FLD 120 FL112(946x554x50x102/102)",
        descriptionES:
          "Intercooler for Freightliner FLD112 FLD 120 FL112(946x554x50x102/102)",
        replacement: ["RHT021"],
      },
      {
        id: 32,
        name: "Quantum Trux Parts",
        title: "QTM-CTR6764",
        images: ["/newImages/QTM-CTR6764-min.png"],
        description: "Tanque de Refrigerante para Freightliner FLD120",
        descriptionES: "Coolant tank for Freightliner FLD120",
      },
      {
        id: 33,
        name: "Quantum Trux Parts",
        title: "QTM-LFI4102",
        images: ["/newImages/QTM-LFI4102-min.png"],
        description: "Lámpara Frontal International Serie 9,000 Izq",
        descriptionES:
          "Headlight Assembly Left for International Series 9100,9200,9400 and 9900 ",
        replacement: ["Newstar S-21408", "3502-928-C95"],
      },
      {
        id: 34,
        name: "Quantum Trux Parts",
        title: "QTM-LDL5004",
        images: ["/newImages/QTM-LDL5004-min.png"],
        description: "Lámpara Direccional para Mack (mismo para Izq. Y Der.)",
        descriptionES: "Directional Lamp Mack CH/CL/CX/CV Models",
        replacement: ["PAI: PSL-5288", "47MO56M"],
      },
      {
        id: 35,
        name: "Quantum Trux Parts",
        title: "QTM-LWL5057R",
        images: ["/newImages/QTM-LWL5057R-min.png"],
        description: "Lámpara de LED Circular  con Borde Rojo 51W, 17 diodos ",
        descriptionES: "Circular LED Light. Red Trim, 51 W, 17 LEDS",
        replacement: ["DF-013R-51W"],
      },
      {
        id: 36,
        name: "Quantum Trux Parts",
        title: "QTM-LEL5156",
        images: ["/newImages/QTM-LEL5156-min.png"],
        description:
          "Lámpara Escolta LED DC12-24V, 40 LEDS, Doble Flash/4 Flash con base magnetica y conexión al enchufe de Cigarrillo.",
        descriptionES:
          "Escorta LED Lamp DC12-24V, 40 LEDS, Double Flash/4 Flash with magnetic base and connection to the Cigarette plug.",
        replacement: ["111016"],
      },
      {
        id: 37,
        name: "Quantum Trux Parts",
        title: "QTM-LLP4002R",
        images: ["/newImages/QTM-LLP4002R-min.png"],
        description: "Lámpara de 8 LED de 4″ / 12 V Roja ",
        descriptionES: "Coolant tank for Freightliner FLD120",
      },
    ],
  },
  {
    brand: "usaPro",
    logo: "/usaProLogo.webp",
    id: 3,
    products: [
      {
        id: 1,
        title: "UPRO-23532333",
        images: ["/UPRO-23532333 - 400px.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 2,
        title: "UPRO-SEA6969",
        images: ["/UPRO-SEA6969 - 400px.png"],
        description:
          "Detroit Diesel Series 60 Crankshaft Rear Seal Sello trasero del cigüeñal Detroit Diesel Series 60",
      },
      {
        id: 3,
        title: "UPRO-62GB2396A",
        images: ["/UPRO-62GB2396A - 400px.png"],
        description:
          "Casquillos de Biela para Mack E7 0.10 mm Connecting Rod Bearing Set for Mack E7 0.10 mm",
      },
      {
        id: 4,
        title: "UPRO-215SB72DP1",
        images: ["/UPRO-215SB72DP1 - 400px.png"],
        description:
          "Casquillos de Bancada para MACK E-6 Standard KIT MAIN BEARING STD E-6",
      },
      {
        id: 5,
        title: "UPRO-1836320C1",
        images: ["/UPRO-1836320C1 - 400px.png"],
        description: "Piston Assy Navistar DT466E T444E",
      },
    ],
  },
  {
    brand: "goodyear",
    logo: "/goodyear.png",
    id: 4,
    products: [
      {
        id: 1,
        title: "1R12-538 1",
        images: ["/1R12-538 1.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 2,
        title: "11R12-538 2",
        images: ["/1R12-538 2.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 3,
        title: "1R12-538",
        images: ["/1R12-538.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 4,
        title: "1R12-603 1",
        images: ["/1R12-603 1.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 5,
        title: "1R12-603 2",
        images: ["/1R12-603 2.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 6,
        title: "1R12-603",
        images: ["/1R12-603.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
    ],
  },
  {
    brand: "grc",
    logo: "/grc.png",
    id: 5,
    products: [
      {
        id: 1,
        title: "85003",
        images: ["/85003.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 2,
        title: "85320",
        images: ["/85320.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 3,
        title: "85724",
        images: ["/85724.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
    ],
  },
  {
    brand: "sampa",
    logo: "/sampa.png",
    id: 6,
    products: [
      {
        id: 1,
        title: "SP 556910 1",
        images: ["/SP 556910 1.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 2,
        title: "SP-559375-KP",
        images: ["/SP-559375-KP.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 3,
        title: "SP 559781-KA",
        images: ["/SP 559781-KA.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
    ],
  },
  {
    brand: "triseal",
    logo: "/triseal.jpeg",
    id: 8,
    products: [
      {
        id: 1,
        title: "WUHL 9082",
        images: ["/WUHL 9082.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 2,
        title: "WUHL 9648",
        images: ["/WUHL 9648-A.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
      {
        id: 3,
        title: "WUHL9781",
        images: ["/WUHL9781-A.png"],
        description:
          "60 Series DetEmpaque para Esmerilar Detroit Diesel S60, 11.1 riot Diesel Head Gasket",
      },
    ],
  },
];

export const featuredProdcuts = [
  {
    id: 1,
    sectionES: "Eje de mando",
    section: "Drive shaft",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-EMC1006",
        images: ["/newImages/QTM-EMC1006-min.png"],
        descriptionES: "Cruceta de 6' Mixta Serie 1710",
        description: "U-Joint 1710 Series Half Round Yoke",
        replacement: ["Precision: 476", "Spicer: 5-675X", "NewStar: S-C473"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-EMG1022",
        images: ["/newImages/QTM-EMG1022-min.png"],
        descriptionES: "Grapas para crucetas SPL170X",
        description: "SPL170 Strap & Bolt Kit SPL170X",
        replacement: ["Spicer: 170-70-18X", "S&S Truck: S-D757"],
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-EMC1017",
        images: ["/newImages/QTM-EMC1017-min.png"],
        descriptionES: "Cruceta",
        description: "U Joint SPL90 Series Greasable",
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-EMB1102",
        images: ["/newImages/QTM-EMB1102-min.png"],
        descriptionES: "Balinera de Centro (Soporte de Cardán) Serie 1710",
        description: "Driveshaft Center Support Bearing",
        replacement: [
          "Federal:  HB88510",
          "Precision: HPE9880",
          "Spicer:  210121-1X",
          "NewStar:  S-1980",
        ],
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-EMR1104",
        images: ["/newImages/QTM-EMR1104-min.png"],
        descriptionES: "Caucho Balinera de Centro HB88508",
        description: "Rubber Cushion for HB88508",
      },
    ],
  },
  {
    id: 2,
    sectionES: "Sistema de aire",
    section: "Air System",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-ASA2021",
        images: ["/newImages/QTM-ASA2021-min.png"],
        descriptionES: "Secador de Aire, AD9",
        description:
          "Air Dryer (Supply Port (1) 1/2 'P.T.  Delivery Port (1) 1/2' P.T.)",
        replacement: ["LAD-5586", "Bendix: 065225"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-APV2051",
        images: ["/newImages/QTM-APV2051-min.png"],
        descriptionES: "Válvula E6 con Pedal y Base",
        description: "E6 Foot Valve with Pedal and Base",
        replacement: ["5396-SN4017A", "FA-11016"],
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-ATC2751",
        images: ["/newImages/QTM-ATC2751-min.png"],
        descriptionES: "Válvula de control-Doble Válvula (Pto & Dump Pump)",
        description: "PTO/Dump Pump Combo Valve",
        replacement: ["S-D522", "329358X"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-AVN2715",
        images: ["/newImages/QTM-AVN2715-min.png"],
        descriptionES: "Valvula Niveladora Tipo Retardo CV",
        description: "Leveling Delay Type CV",
        replacement: ["MACK: 20QE2373"],
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-AFS2653",
        images: ["/newImages/QTM-AFS2653-min.png"],
        descriptionES: "Valvula de Freno ABS Completa",
        description: "ABS Axle Package Assy",
        replacement: ["4725001230"],
      },
    ],
  },
  {
    id: 3,
    sectionES: "Eje y rueda",
    section: "Axis and wheels",
    brandImageId: 2,
    products: [
      {
        id: 1,
        name: "Eagle Parts",
        title: "EAG-TCR5572",
        images: ["/EAG-TCR5572 - 400px.png"], // EXISTE
        descriptionES: "Cuña de Rueda Estilo 'F' de 3/4",
        description: "Wheel Clamp, F Style, 1-1/2 X 2-7/8 X 2-1/2 X 3/4",
        replacement: ["E5571A", "09-612317", "W-96", "52-1301", "R005571AG"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-RRT3108",
        images: ["/newImages/QTM-RRT3108-min.png"],
        descriptionES: "Retenedora de Rueda  para ejes de 34,000",
        description: "Oil Bath Wheel Seal ",
        replacement: ["370023A"],
      },
      {
        id: 3,
        name: "Eagle Parts",
        title: "EAG-RRT8408",
        images: ["/newImages/EAG-RRT8408-min.png"],
        descriptionES: "Rines 22.5x8.25 de Tornillos.",
        description: "22.5 X 8.25 cone lock nut, 'hub-pilot' in white",
        replacement: ["28408PW"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-RTR3215",
        images: ["/newImages/QTM-RTR3215-min.png"],
        descriptionES: "TAPA DE 6 HUECOS",
        description: "Cast Aluminum Hub Cap",
        replacement: ["343-4009"],
      },
      {
        id: 5,
        title: "EAG-TWS8980",
        name: "Eagle Parts",
        images: ["/newImages/EAG-TWS8980-min.png"],
        descriptionES: "Tornillo Milimetrico",
        description: "Metric Stud",
        replacement: ["Euclid:  E8980"],
      },
    ],
  },
  {
    id: 4,
    sectionES: "Partes electricas",
    section: "Electrical parts",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-LMA5550",
        images: ["/newImages/QTM-LMA5550-min.png"],
        descriptionES: "Motor de Arranque (Starter) 42MT, 12V, 11 dientes",
        description: "Starter Motor (Starter) 42MT, 12V, 11 teeth",
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-SLN5781",
        images: ["/newImages/QTM-SLN5781-min.png"],
        descriptionES: "Selenoide 42MT",
        description: "12V 42MT Starter Solenoid",
        replacement: ["Delco:  1115593"],
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-LIR5302",
        images: ["/newImages/QTM-LIR5302-min.png"],
        descriptionES: "Interruptor de Relay, 4 terminales, continuo, Dynatard",
        description: "Realy Switch 4 Pole, Continuous, Dynatard ",
        replacement: ["MAK 2MR377"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-LIM5501",
        images: ["/newImages/QTM-LIM5501-min.png"],
        descriptionES:
          "Interruptor de Arrancador (Starter) Abierto para Mack y Navistar",
        description: "Reverse Switch",
        replacement: ["MAK 1MR2297", "NAV 454925C1"],
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-LAT5600",
        images: ["/newImages/QTM-LAT5600-min.png"],
        descriptionES: "Alternador 130Amp",
        description: "Alternator 130 Amps, 12v, J180 Hinge",
        replacement: ["Delco:  19020309"],
      },
    ],
  },
  {
    id: 5,
    sectionES: "Accesorios para puertas y espejos",
    section: "Accessories for doors and mirrors",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-CMP6008",
        images: ["/newImages/QTM-CMP6008-min.png"],
        descriptionES:
          "Manigueta Exterior de Puerta para Freightliner Columbia y Century (Llavín incluído) Izq.",
        description: "Door Handle, LH Columbia Class (1998-2003)",
        replacement: ["A18-42228-000", "New Star:  S-18817"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-CCP6050",
        images: ["/newImages/QTM-CCP6050-min.png"],
        descriptionES: "Cerradura para Puerta Derecha para Mack DM, R y U",
        description: "Door Latch (RH) for Mack R/RB/RD/DM Models",
        replacement: ["MAK 62QS423R"],
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-CES6149",
        images: ["/newImages/QTM-CES6149 - 50-min.png"],
        descriptionES: "Espejo para Capota VOLVO Cromado Izq.",
        description: "Hood Mirror for VOLVO CHROME L",
        replacement: ["01-110055CH"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-CPA6216",
        images: ["/newImages/QTM-CPA6216-min.png"],
        descriptionES: "Parrilla para International PROSTAR",
        description: "Truck Front Grill forPROSTAR International",
        replacement: ["01-210001"],
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-CBS6317",
        images: ["/newImages/QTM-CBS6317 - 18-min.png"],
        descriptionES: "Bisel Cromado para International Serie 9,000 Izq.",
        description: "Headlight Bezel for  International 9,000 Series (LH)",
        replacement: ["Newstar: S-21412", "Inter: 2505-370-C"],
      },
    ],
  },
  {
    id: 6,
    sectionES: "Escape",
    section: "Exhaust",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-XDE8002",
        images: ["/newImages/QTM-XDE8002-min.png"],
        descriptionES: "Codo de 5″ x90 de patas largas",
        description:
          "Exhaust Elbow-5″ 90 Degree Elbow 20″ x 20″ ID-OD – Aluminized",
        replacement: ["11ME241"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-XAH8364",
        images: ["/newImages/QTM-XAH8364-min.png"],
        descriptionES: "Abrazadera de 5″ Para Turbo Con Labio",
        description: "5″ Turbo Outlet Clamp",
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-XRD8033",
        images: ["/newImages/QTM-XRD8033-min.png"],
        descriptionES: "Reducción 5″ a 4″",
        description:
          "Connector-Reducer Coupler Aluminized 5″ ID to 4″ ID x 6″ Long",
        replacement: ["RI540"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-XFT8251",
        images: ["/newImages/QTM-XFT8251-min.png"],
        descriptionES: "Tubo Flexible de 5″ (25 pies por rollo)",
        description: "Heavy Weight Flexible Tubing 5″ x 25'",
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-XSM8300",
        images: ["/newImages/QTM-XSM8300-min.png"],
        descriptionES: "Silenciador 51″x10″x5″x5″44.5″",
        description: "Horizontal or Vertical Muffler 51″x10″x5″x5″44.5″",
        replacement: ["5839-86682M"],
      },
    ],
  },
  {
    id: 7,
    sectionES: "Quinta rueda y patas de furgon",
    section: "Fifth wheel and landing gear",
    brandImageId: 2,
    products: [
      {
        id: 1,
        name: "Eagle Parts",
        title: "EAG-FQR3003",
        images: ["/newImages/EAG-FQR3003-min.png"],
        descriptionES: "Quinta Rueda Tipo Holland Con base incluida.",
        description: "Fifth Wheel, Holland type w/ base included",
        replacement: ["BP3003"],
      },
      {
        id: 2,
        name: "Eagle Parts",
        title: "EAG-FQR0050",
        images: ["/newImages/EAG-FQR0050-min.png"],
        descriptionES: "Pin Para Quinta Rueda",
        description: "Fifth Wheel Coupling Pin",
        replacement: ["CM-W50"],
      },
      {
        id: 3,
        name: "Eagle Parts",
        title: "EAG-FQR7296",
        images: ["/newImages/EAG-FQR7296-min.png"],
        descriptionES: "Kit de Repación para Quinta Rueda Holland",
        description: "Holland Fifth Wheel Minor Repair Kit",
        replacement: ["RK35107296"],
      },
      {
        id: 4,
        name: "Eagle Parts",
        title: "EAG-FPF6110",
        images: ["/newImages/EAG-FPF6110-min.png"],
        descriptionES: "Juego Patas de Furgon, Reforzadas, 30T",
        description: "30 Tons Landing Gear",
        replacement: ["26110"],
      },
      {
        id: 5,
        name: "Eagle Parts",
        title: "EAG-FPF0001",
        images: ["/newImages/EAG-FPF0001-min.png"],
        descriptionES: "Patin para Patas Furgón",
        description: "Landing Gear Sand Shoe",
      },
    ],
  },
  {
    id: 8,
    section: "Suspension",
    sectionES: "Suspensión",
    brandImageId: 2,
    products: [
      {
        id: 1,
        name: "Eagle Parts",
        title: "EAG-HRR2727",
        images: ["/newImages/EAG-HRR2727-min.png"],
        descriptionES: "Resorte de 3 Hojas de media curva",
        description: "Trailer Spring 3 Leaf, Medium 4-1/2″ Arch.",
        replacement: ["TRA-2727"],
      },
      {
        id: 2,
        name: "Eagle Parts",
        title: "EAG-SBT2639",
        images: ["/newImages/EAG-SBT2639-min.png"],
        descriptionES: "Barra Tensora Hembra con Buje de 2.75, hueco 5/8″",
        description: "Two Piece Torque Rod End",
        replacement: ["E2639", "TMRU610 (Automann)"],
      },
      {
        id: 3,
        name: "Eagle Parts",
        title: "EAG-SSB2830",
        images: ["/newImages/EAG-SSB2830-min.png"],
        descriptionES: "BALANCIN FREUHAUF",
        description: "Fruehauf F-2 Equalizer",
        replacement: ["E2830", "338-715", "FR-2691", "EQ015"],
      },
      {
        id: 4,
        name: "Eagle Parts",
        title: "EAG-SBT5680",
        images: ["/newImages/EAG-SBT5680-min.png"],
        descriptionES:
          "Barra Tensora macho (Hasta 35″) con Altura 8″ y Rosca 1-1/4″-12",
        description: "Torque Rod End (Up to 35″), H:  8″, THREADS:  1-1/4″-12",
        replacement: ["TMRU680", "Dayton 345-680", "Flagg MR680"],
      },
      {
        id: 5,
        name: "Eagle Parts",
        title: "EAG-SCS2919PU",
        images: ["/newImages/EAG-SCS2919PU-min.png"],
        descriptionES: "Sapo Mediano (Superior) Poliuretano",
        description: "Mack Insulator Pad Poly",
        replacement: ["10QK370-UB"],
      },
    ],
  },
  {
    id: 9,
    sectionES: "Componentes de dirección",
    section: "Steering parts",
    brandImageId: 2,
    products: [
      {
        id: 1,
        name: "Eagle Parts",
        title: "EAG-DTD0411R",
        images: ["/newImages/EAG-DTD0411R-min.png"],
        descriptionES: "Terminal de dirección Inter Largo",
        description: "Outer Tie Rod End (RH) 9.18″",
        replacement: ["ES-411R"],
      },
      {
        id: 2,
        name: "Eagle Parts",
        title: "EAG-DTB4272",
        images: ["/newImages/EAG-DTB4272-min.png"],
        descriptionES: "Tercer Brazo Mack CH (34.75″ nominal /centro a centro)",
        description: "Drag Link for Mack  - 34.75″",
        replacement: ["MAK13QC427AM2"],
      },
      {
        id: 3,
        name: "Eagle Parts",
        title: "EAG-DBT2514",
        images: ["/newImages/EAG-DBT2514-min.png"],
        descriptionES: "Brazo de Torque Fijo",
        description: "Rigid Torque Arm 15-7/16 Center To Center",
        replacement: ["E2514"],
      },
      {
        id: 4,
        name: "Eagle Parts",
        title: "EAG-DTB3426",
        images: ["/newImages/EAG-DTB3426-min.png"],
        descriptionES:
          "Tercer Brazo (Barra de Arrastre) 18 3/4″ centro a centro",
        description: "Drag Link for Mack - 18.75″",
        replacement: ["MAK-13QC426A", "Dayton 346-578"],
      },
      {
        id: 5,
        name: "Eagle Parts",
        title: "EAG-DTB5366",
        images: ["/newImages/EAG-DTB5366-min.png"],
        descriptionES: "Tercer Brazo Navistar Stud Center-Stud Center: 18.14”",
        description: "Drag Link for International - 18.14”",
        replacement: [
          "E5366",
          "DS-979",
          "Dayton:  346-249",
          "Navistar:  480645C92",
        ],
      },
    ],
  },
  {
    id: 10,
    sectionES: "Tanques de reserva",
    section: "Surge tanks and radiators",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-CTR6760",
        images: ["/newImages/QTM-CTR6760-min.png"],
        descriptionES: "Tanque de Refrigerante para MACK GU Y CV",
        description: "Coolant tank for MACK GU Y CV",
        replacement: ["22061290"],
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-CTC6714",
        images: ["/newImages/QTM-CTC6714-min.png"],
        descriptionES: "Tapa Tanque de Expansión de Líquido Refrigerante M2",
        description: "Surge Tank Cap M2",
        replacement: ["05-180002", "M2"],
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-RRF8506",
        images: ["/newImages/QTM-RRF8506-min.png"],
        descriptionES:
          "Radiador Freightliner Century, Columbia and Classic XL 2008-2011 (987x958.1x58x63.5/63.5)",
        description:
          "Radiator Freightliner Century, Columbia and Classic XL 2008-2011 (987x958.1x58x63.5/63.5)",
        replacement: ["05-26619-024"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-RIC8551",
        images: ["/newImages/QTM-RIC8551-min.png"],
        description:
          "Intercooler for Freightliner FLD112 FLD 120 FL112(946x554x50x102/102)",
        descriptionES:
          "Intercooler for Freightliner FLD112 FLD 120 FL112(946x554x50x102/102)",
        replacement: ["RHT021"],
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-CTR6764",
        images: ["/newImages/QTM-CTR6764-min.png"],
        descriptionES: "Tanque de Refrigerante para Freightliner FLD120",
        description: "Coolant tank for Freightliner FLD120",
        replacement: ["603-5219"],
      },
    ],
  },
  {
    id: 11,
    sectionES: "Lamparas y escoltas",
    section: "Lamps and strobe lights",
    brandImageId: 3,
    products: [
      {
        id: 1,
        name: "Quantum Trux Parts",
        title: "QTM-LFI4103",
        images: ["/newImages/QTM-LFI4103-min.png"],
        descriptionES: "Lámpara Frontal International Serie 9,000 Izq",
        description:
          "Headlight Assembly Left for International Series 9100,9200,9400 and 9900 ",
      },
      {
        id: 2,
        name: "Quantum Trux Parts",
        title: "QTM-LDL5004",
        images: ["/newImages/QTM-LDL5004-min.png"],
        descriptionES: "Lámpara Direccional para Mack (mismo para Izq. Y Der.)",
        description: "Directional Lamp Mack CH/CL/CX/CV Models",
      },
      {
        id: 3,
        name: "Quantum Trux Parts",
        title: "QTM-LWL5057R",
        images: ["/newImages/QTM-LWL5057R-min.png"],
        descriptionES: "Lámpara de LED Circular  con Borde Rojo 51W, 17 diodos ",
        description: "Circular LED Light. Red Trim, 51 W, 17 LEDS",
        replacement: ["DF-013R-51W"],
      },
      {
        id: 4,
        name: "Quantum Trux Parts",
        title: "QTM-LEL5156",
        images: ["/newImages/QTM-LEL5156-min.png"],
        descriptionES:
          "Lámpara Escolta LED DC12-24V, 40 LEDS, Doble Flash/4 Flash con base magnetica y conexión al enchufe de Cigarrillo.",
        description:
          "Escort LED Lamp DC12-24V, 40 LEDS, Double Flash/4 Flash with magnetic base and connection to the Cigarette plug.",
      },
      {
        id: 5,
        name: "Quantum Trux Parts",
        title: "QTM-LLP4002R",
        images: ["/newImages/QTM-LLP4002R-min.png"],
        descriptionES: "Lámpara de 8 LED de 4″ / 12 V Roja ",
        description: "Coolant tank for Freightliner FLD120",
      },
    ],
  },
];

export const bannerImages = [
  { image: "/comp1H.jpg" },
  { image: "/comp2H.jpg" },
  { image: "/comp3V.jpg" },
  { image: "/comp4H.jpg" },
  { image: "/comp8V.jpg" },
  { image: "/comp7H.jpg" },
  { image: "/comp6H.jpg" },
];
